-   id: branch-name
    name: enforce branch name pattern
    description: 'enforce branch name pattern'
    entry: gitgud
    always_run: true
    args: ["branch-name"]
    language: golang

-   id: commit-msg
    name: enforce commit message format
    description: 'enforce commit message format'
    entry: gitgud
    always_run: true
    stages: [commit-msg]
    args: ["commit-msg"]
    language: golang
