-   id: branch-name
    name: Enforce branch name pattern
    description: 'Enforce branch name pattern'
    entry: gitgud
    always_run: true
    args: ["branch-name"]
    language: golang

-   id: commit-msg
    name: Enforce commit message format
    description: 'Enforce commit message format'
    entry: gitgud
    always_run: true
    args: ["commit-msg"]
    language: golang
